# Generated by Django 3.0.4 on 2020-04-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room1', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('room2', models.IntegerField()),
                ('room3', models.IntegerField()),
                ('room4', models.IntegerField()),
            ],
        ),
    ]
