# Generated by Django 3.0.4 on 2020-04-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('subject1', models.CharField(max_length=100)),
                ('subject2', models.CharField(max_length=100)),
                ('subject3', models.CharField(max_length=100)),
                ('subject4', models.CharField(max_length=100)),
                ('teacher1', models.CharField(max_length=100)),
                ('teacher2', models.CharField(max_length=100)),
                ('teacher3', models.CharField(max_length=100)),
                ('teacher4', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
