# Generated by Django 3.0.4 on 2020-04-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20200415_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcourse',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='priority',
        ),
    ]
