# Generated by Django 3.0.4 on 2020-04-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20200418_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcourse',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='addcourse',
            name='teachers',
        ),
        migrations.AddField(
            model_name='addcourse',
            name='subject1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='subject2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='subject3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='subject4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='teacher1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='teacher2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='teacher3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addcourse',
            name='teacher4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
