# Generated by Django 3.0.4 on 2020-04-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20200418_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1', models.CharField(max_length=100)),
                ('section2', models.CharField(max_length=100)),
                ('section3', models.CharField(max_length=100)),
                ('section4', models.CharField(max_length=100)),
            ],
        ),
    ]
